#!/usr/bin/env bash
set -euo pipefail

# Prefer Solana 1.18.17 CLI (what Anchor 0.30.1 expects). cargo-build-sbf in that
# tree is already symlinked to the Agave stable binary — that is fine.
SOLANA_118="$HOME/.local/share/solana/install/releases/1.18.17/solana-release/bin"
STABLE_BIN="$HOME/.local/share/solana/install/releases/stable-6a8c724a9ed8f093127ef6066e0bcfb074193cc3/solana-release/bin"
export PATH="$SOLANA_118:$STABLE_BIN:$HOME/.cargo/bin:$HOME/.avm/bin:$PATH"

# Prevent Anchor from trying to fetch solana-install if something is missing.
export PATH="$HOME/bin:$PATH"
mkdir -p "$HOME/bin"
cat > "$HOME/bin/solana-install" <<'EOF'
#!/usr/bin/env bash
echo "solana-install stub: skipping (tools already present)" >&2
exit 0
EOF
chmod +x "$HOME/bin/solana-install"

REPO="/mnt/c/Users/choum/Desktop/GleanAI"
TARGET_DIR="$HOME/glean-anchor-target"
mkdir -p "$TARGET_DIR"
export CARGO_TARGET_DIR="$TARGET_DIR"

echo "==> versions"
solana --version
anchor --version
cargo-build-sbf --version
which cargo-build-sbf
which solana

echo "==> build distributor (platform-tools v1.41)"
cd "$REPO"
if [ ! -d "$HOME/.cache/solana/v1.41/platform-tools/rust/lib" ]; then
  echo "ERROR: platform-tools v1.41 missing. Run scripts/parallel-dl.py v1.41 then extract-tools.sh" >&2
  exit 1
fi
# platform-tools v1.41 cargo cannot read lockfile v4 (generated by host rustc)
if grep -q '^version = 4$' Cargo.lock 2>/dev/null; then
  echo "regenerating Cargo.lock for older sbf cargo"
  rm -f Cargo.lock
fi
cargo-build-sbf --tools-version v1.41 --skip-tools-install \
  --manifest-path programs/glean-distributor/Cargo.toml

echo "==> copy deploy artifacts into repo target (for Anchor.toml paths)"
mkdir -p "$REPO/target/deploy"
if [ -f "$TARGET_DIR/deploy/glean_distributor.so" ]; then
  cp -f "$TARGET_DIR/deploy/glean_distributor.so" "$REPO/target/deploy/"
fi
# Keep existing keypair if present
if [ -f "$REPO/target/deploy/glean_distributor-keypair.json" ]; then
  echo "keypair already in repo target/deploy"
elif [ -f "$TARGET_DIR/deploy/glean_distributor-keypair.json" ]; then
  cp -f "$TARGET_DIR/deploy/glean_distributor-keypair.json" "$REPO/target/deploy/"
fi

echo "==> done"
ls -lh "$REPO/target/deploy/" || true
